# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PincodeServiceability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_available', models.BooleanField(default=False)),
                ('pickup_available', models.BooleanField(default=False)),
                ('regular_delivery_available', models.BooleanField(default=False)),
                ('regular_pickup_available', models.BooleanField(default=False)),
                ('cod_available', models.BooleanField(default=False)),
                ('logistics_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.LogisticsPartner')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Pincode')),
            ],
        ),
    ]
