# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logisticspartner',
            options={'verbose_name': 'Logistics Partner', 'verbose_name_plural': 'Logistics Partners'},
        ),
        migrations.AlterModelOptions(
            name='pincodeserviceability',
            options={'verbose_name': 'Pincode Serviceability', 'verbose_name_plural': 'Pincode Serviceability'},
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 19, 22, 41, 31, 814899)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 19, 22, 41, 34, 411768)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincodeserviceability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 19, 22, 41, 37, 719857)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pincodeserviceability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 19, 22, 41, 40, 28002)),
            preserve_default=False,
        ),
    ]
