# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20160719_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincodeserviceability',
            name='ou_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
