# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.CharField(db_index=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=11)),
                ('mobile_verification', models.BooleanField(default=False)),
                ('email_verification', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, default=b'India', max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=11)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=11)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.CharField(db_index=True, max_length=11)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=11)),
                ('mobile_verification', models.BooleanField(default=False)),
                ('email_verification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, default=b'India', max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=11)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Seller')),
            ],
        ),
    ]
