# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('tin_number', models.CharField(blank=True, max_length=20)),
                ('buyer_interest', models.TextField(blank=True)),
                ('customer_type', models.CharField(blank=True, max_length=20)),
                ('buying_capacity', models.CharField(blank=True, max_length=20)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('tin_number', models.CharField(blank=True, max_length=20)),
                ('account_holders_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=18)),
                ('ifsc', models.CharField(max_length=11)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('name_on_pan', models.CharField(blank=True, max_length=100)),
                ('dob_on_pan', models.DateField(blank=True, null=True)),
                ('pan_verification', models.BooleanField(default=0)),
                ('tin_verification', models.BooleanField(default=0)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Seller')),
            ],
        ),
    ]
