# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buyerdetails_sellerdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerdetails',
            old_name='tin_number',
            new_name='vat_tin',
        ),
        migrations.RenameField(
            model_name='sellerdetails',
            old_name='vat_number',
            new_name='cst',
        ),
        migrations.RenameField(
            model_name='sellerdetails',
            old_name='tin_number',
            new_name='vat_tin',
        ),
        migrations.RemoveField(
            model_name='buyerdetails',
            name='vat_number',
        ),
        migrations.AddField(
            model_name='buyeraddress',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='buys_from',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='cst',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='purchasing_states',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='selleraddress',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
