# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160421_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holders_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=18)),
                ('ifsc', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('branch_city', models.CharField(blank=True, max_length=50)),
                ('branch_pincode', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='account_holders_name',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='ifsc',
        ),
        migrations.AddField(
            model_name='buyer',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerbankdetails',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Seller'),
        ),
    ]
