# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160422_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeraddress',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
