# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_buyeraddress_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='company_profile',
            field=models.TextField(blank=True),
        ),
    ]
