# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_seller_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 8, 15, 39, 50, 449786, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyeraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 8, 15, 39, 56, 512795, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 8, 15, 40, 2, 506011, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 8, 15, 40, 9, 526766, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selleraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 8, 15, 40, 15, 727747, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selleraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 8, 15, 40, 25, 330747, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerbankdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 8, 15, 40, 30, 293029, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerbankdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 8, 15, 40, 34, 360763, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 8, 15, 40, 39, 979752, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 8, 15, 40, 54, 66741, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
