# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160508_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_conditions',
            field=models.TextField(blank=True),
        ),
    ]
