# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_seller_seller_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdetails',
            name='purchase_duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='concerned_person',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='seller',
            name='concerned_person_number',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='seller',
            name='show_online',
            field=models.BooleanField(default=True),
        ),
    ]
