# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160516_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyeraddress',
            old_name='address',
            new_name='address_line',
        ),
        migrations.RenameField(
            model_name='buyeraddress',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='buyeraddress',
            old_name='country',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='buyeraddress',
            old_name='pincode',
            new_name='pincode_number',
        ),
        migrations.RenameField(
            model_name='buyeraddress',
            old_name='state',
            new_name='state_name',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='address',
            new_name='address_line',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='country',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='pincode',
            new_name='pincode_number',
        ),
        migrations.RenameField(
            model_name='selleraddress',
            old_name='state',
            new_name='state_name',
        ),
        migrations.RemoveField(
            model_name='buyerdetails',
            name='buyer_interest',
        ),
    ]
