# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_new_in_product_matrix'),
        ('users', '0013_auto_20160623_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('shortlisted', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
                ('shortlisted_time', models.DateTimeField(blank=True, null=True)),
                ('disliked_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
                ('buyer_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BuyerInterest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
            options={
                'ordering': ['-product__id'],
            },
        ),
    ]
