# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20160630_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='facebook_profile_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internaluser',
            name='linkedin_profile_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
