# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20160702_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='whatsapp_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='buyer',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='whatsapp_sharing_active',
            field=models.BooleanField(default=True),
        ),
    ]
