# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20160703_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='test_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='test_seller',
            field=models.BooleanField(default=False),
        ),
    ]
