# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_buyerproductlanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerproductresponse',
            name='has_swiped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyerproductresponsehistory',
            name='has_swiped',
            field=models.BooleanField(default=False),
        ),
    ]
