# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20160716_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPanelInstructionsTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_closed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyer Panel Instructions Tracking',
                'verbose_name_plural': 'Buyer Panel Instructions Tracking',
                'default_related_name': 'buyerpanelinstructionstracking',
            },
        ),
        migrations.AlterModelOptions(
            name='businesstype',
            options={'verbose_name': 'Business Type', 'verbose_name_plural': 'Business Types'},
        ),
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['-id'], 'verbose_name': 'Buyer', 'verbose_name_plural': 'Buyers'},
        ),
        migrations.AlterModelOptions(
            name='buyeraddress',
            options={'verbose_name': 'Buyer Address', 'verbose_name_plural': 'Buyer Addresses'},
        ),
        migrations.AlterModelOptions(
            name='buyerbuysfrom',
            options={'verbose_name': 'Buyer Buys From', 'verbose_name_plural': 'Buyer Buys From'},
        ),
        migrations.AlterModelOptions(
            name='buyerdetails',
            options={'verbose_name': 'Buyer Details', 'verbose_name_plural': 'Buyer Details'},
        ),
        migrations.AlterModelOptions(
            name='buyerinterest',
            options={'verbose_name': 'Buyer Interest', 'verbose_name_plural': 'Buyer Interests'},
        ),
        migrations.AlterModelOptions(
            name='buyerinteresthistory',
            options={'verbose_name': 'Buyer Interest History', 'verbose_name_plural': 'Buyer Interest History'},
        ),
        migrations.AlterModelOptions(
            name='buyerproductlanding',
            options={'verbose_name': 'Buyer Product Landing', 'verbose_name_plural': 'Buyer Product Landings'},
        ),
        migrations.AlterModelOptions(
            name='buyerproductresponse',
            options={'verbose_name': 'Buyer Product Response', 'verbose_name_plural': 'Buyer Product Responses'},
        ),
        migrations.AlterModelOptions(
            name='buyerproductresponsehistory',
            options={'verbose_name': 'Buyer Product Response History', 'verbose_name_plural': 'Buyer Product Response History'},
        ),
        migrations.AlterModelOptions(
            name='buyerproducts',
            options={'ordering': ['-product__id'], 'verbose_name': 'Buyer Product', 'verbose_name_plural': 'Buyer Products'},
        ),
        migrations.AlterModelOptions(
            name='buyerpurchasingstate',
            options={'verbose_name': 'Buyer Purchasing State', 'verbose_name_plural': 'Buyer Purchasing States'},
        ),
        migrations.AlterModelOptions(
            name='buyersharedproductid',
            options={'verbose_name': 'Buyer Shared Product ID', 'verbose_name_plural': 'Buyer Shared Product IDs'},
        ),
        migrations.AlterModelOptions(
            name='internaluser',
            options={'verbose_name': 'Internal User', 'verbose_name_plural': 'Internal Users'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['-id'], 'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AlterModelOptions(
            name='selleraddress',
            options={'verbose_name': 'Seller Address', 'verbose_name_plural': 'Seller Addresses'},
        ),
        migrations.AlterModelOptions(
            name='sellerbankdetails',
            options={'verbose_name': 'Seller Bank Details', 'verbose_name_plural': 'Seller Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='sellerdetails',
            options={'verbose_name': 'Seller Details', 'verbose_name_plural': 'Seller Details'},
        ),
        migrations.AddField(
            model_name='buyerpanelinstructionstracking',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer'),
        ),
    ]
