# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20160719_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdetails',
            name='buyer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.BusinessType'),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='seller_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.BusinessType'),
        ),
    ]
