# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20160722_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerproducts',
            name='disliked_time',
        ),
        migrations.RemoveField(
            model_name='buyerproducts',
            name='shortlisted_time',
        ),
    ]
