# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20160725_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerproductresponse',
            name='buyer_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BuyerProducts'),
        ),
    ]
