# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20160726_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerproducts',
            options={'ordering': ['-id'], 'verbose_name': 'Buyer Product', 'verbose_name_plural': 'Buyer Products'},
        ),
    ]
