# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-18 13:03
from __future__ import unicode_literals

from django.db import migrations

def create_buyer_address_history(apps, schema_editor):

	Buyer = apps.get_model("users", "Buyer")
	BuyerAddress = apps.get_model("users", "BuyerAddress")
	BuyerAddressHistory = apps.get_model("users", "BuyerAddressHistory")

	buyers = Buyer.objects.all()
	for buyerPtr in buyers:

		buyerAddressHistoryPtr = BuyerAddressHistory.objects.filter(buyer=buyerPtr)

		if not buyerAddressHistoryPtr.exists():
			buyerAddressPtr = BuyerAddress.objects.filter(buyer=buyerPtr)
			if len(buyerAddressPtr) == 0:
				buyeraddress["address"] = ""
				buyeraddress["landmark"] = ""
				buyeraddress["contact_number"] = ""
				buyeraddress["pincode"] = ""
				buyeraddress["city"] = ""
				buyeraddress["state"] = ""
				buyerAddressPtr = BuyerAddress(buyer=buyerPtr)
				populateBuyerAddress(buyerAddressPtr, buyeraddress)
				buyerAddressPtr.save()
			else:
				buyerAddressPtr = buyerAddressPtr[0]

			newBuyerAddressHistory = BuyerAddressHistory()
			newBuyerAddressHistory.populateFromBuyerAddress(buyerAddressPtr)
			newBuyerAddressHistory.save()

class Migration(migrations.Migration):

	dependencies = [
		('users', '0029_buyeraddresshistory'),
	]

	operations = [
		migrations.RunPython(create_buyer_address_history),
	]