# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20160818_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyeraddresshistory',
            options={'verbose_name': 'Buyer Address History', 'verbose_name_plural': 'Buyer Address History'},
        ),
    ]
