# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160719_2241'),
        ('users', '0031_auto_20160819_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAddressHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=50)),
                ('city_name', models.CharField(blank=True, max_length=50)),
                ('state_name', models.CharField(blank=True, max_length=50)),
                ('country_name', models.CharField(blank=True, default=b'India', max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=11)),
                ('pincode_number', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pincode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Pincode')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Seller')),
                ('selleraddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SellerAddress')),
            ],
            options={
                'verbose_name': 'Seller Address History',
                'verbose_name_plural': 'Seller Address History',
            },
        ),
    ]
