# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20160902_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='store_slug',
            field=models.TextField(blank=True),
        ),
    ]
