# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 06:48
from __future__ import unicode_literals

from django.db import migrations

from django.template.defaultfilters import slugify

def create_buyer_store_slug(apps, schema_editor):

	Buyer = apps.get_model("users", "Buyer")
	buyers = Buyer.objects.all()
	for buyerPtr in buyers:
		if buyerPtr.company_name != "":
			buyerPtr.store_slug = slugify(buyerPtr.company_name)
		else:
			buyerPtr.store_slug = slugify(buyerPtr.name)
		buyerPtr.save()

class Migration(migrations.Migration):

	dependencies = [
		('users', '0035_buyer_store_slug'),
	]

	operations = [
		migrations.RunPython(create_buyer_store_slug),
	]
