# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20160905_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='store_url',
            field=models.TextField(blank=True),
        ),
    ]
