# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 08:15
from __future__ import unicode_literals

from django.db import migrations

def create_buyer_store_url(apps, schema_editor):

	Buyer = apps.get_model("users", "Buyer")
	buyers = Buyer.objects.all()
	for buyerPtr in buyers:
		buyerPtr.store_url = "{}-{}".format(buyerPtr.store_slug,buyerPtr.id)
		buyerPtr.save()

class Migration(migrations.Migration):

	dependencies = [
		('users', '0037_buyer_store_url'),
	]

	operations = [
		migrations.RunPython(create_buyer_store_url),
	]
