# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20160719_2241'),
        ('users', '0038_auto_20160906_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerStoreLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('sizes', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('mobile_number', models.CharField(max_length=11)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
            options={
                'verbose_name': 'Buyer Store Lead',
                'verbose_name_plural': 'Buyer Store Leads',
            },
        ),
    ]
