# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_buyer_store_global_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerproductresponse',
            name='store_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
