# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20160719_2241'),
        ('users', '0043_auto_20160912_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Seller')),
            ],
            options={
                'verbose_name': 'Seller Category',
                'verbose_name_plural': 'Seller Categories',
            },
        ),
    ]
