# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20160916_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=11)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('otp_number', models.CharField(blank=True, max_length=10)),
                ('messages_sent', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyer Registration',
                'verbose_name_plural': 'Buyer Registrations',
            },
        ),
    ]
