# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-13 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_buyerregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerregistration',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
