# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20161113_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
            ],
            options={
                'verbose_name': 'Buyer Refresh Token',
                'verbose_name_plural': 'Buyer Refresh Tokens',
            },
        ),
        migrations.CreateModel(
            name='BuyerRefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
            ],
            options={
                'verbose_name': 'Buyer Refresh Token',
                'verbose_name_plural': 'Buyer Refresh Tokens',
            },
        ),
        migrations.AddField(
            model_name='buyeraccesstoken',
            name='buyer_refresh_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BuyerRefreshToken'),
        ),
    ]
