# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20161114_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyeraccesstoken',
            options={'verbose_name': 'Buyer Access Token', 'verbose_name_plural': 'Buyer Access Tokens'},
        ),
    ]
