# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_buyerforgotpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeraddress',
            name='alias',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buyeraddresshistory',
            name='alias',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
