# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20161128_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeraddress',
            name='client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buyeraddresshistory',
            name='client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
