# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20161215_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='store_global_discount',
            new_name='store_global_margin',
        ),
        migrations.RenameField(
            model_name='buyerproductresponse',
            old_name='store_discount',
            new_name='store_margin',
        ),
    ]
