# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20161220_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='store_active',
            field=models.BooleanField(default=False),
        ),
    ]
