# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 14:01
from __future__ import unicode_literals

from django.db import migrations

from django.template.defaultfilters import slugify

def edit_store_urls(apps, schema_editor):

	Buyer = apps.get_model("users", "Buyer")

	buyers = Buyer.objects.all()

	storeNameArr = []
	for buyer in buyers:
		store_url = buyer.store_slug
		if store_url in storeNameArr:
			company_name_slug = slugify(buyer.company_name)
			if company_name_slug == "":
				company_name_slug = "boutique"
			store_url = "store-" + company_name_slug + "-"+ str(buyer.id*9)
		storeNameArr.append(store_url)
		buyer.store_url = store_url
		buyer.store_active = True
		buyer.save()

class Migration(migrations.Migration):

	dependencies = [
		('users', '0055_buyer_store_active'),
	]

	operations = [
		migrations.RunPython(edit_store_urls),
	]
