# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 08:06
from __future__ import unicode_literals

from django.db import migrations

def edit_store_urls(apps, schema_editor):

	BuyerAddress = apps.get_model("users", "BuyerAddress")
	BuyerAddressHistory = apps.get_model("users", "BuyerAddressHistory")

	buyersAddresses = BuyerAddress.objects.all()
	buyersAddressHistories = BuyerAddressHistory.objects.all()

	storeNameArr = []
	for buyerAddress in buyersAddresses:
		buyerAddress.priority = 0
		buyerAddress.alias = "Store"
		buyerAddress.save()
	for buyerAddress in buyersAddressHistories:
		buyerAddress.priority = 0
		buyerAddress.alias = "Store"
		buyerAddress.save()


class Migration(migrations.Migration):

	dependencies = [
		('users', '0056_auto_20161223_1401'),
	]

	operations = [
		migrations.RunPython(edit_store_urls),
	]
