# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20161227_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyeraddress',
            options={'ordering': ['priority'], 'verbose_name': 'Buyer Address', 'verbose_name_plural': 'Buyer Addresses'},
        ),
    ]
