# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 07:45
from __future__ import unicode_literals

from django.db import migrations

def delete_to_show_online(apps, schema_editor):

	Seller = apps.get_model("users", "Seller")
	Product = apps.get_model("catalog", "Product")

	sellers = Seller.objects.filter(delete_status=1)

	for seller in sellers:
		seller.delete_status =0
		seller.show_online = 0
		seller.save()

		sellerProducts = Product.objects.filter(seller_id=seller.id)

		for product in sellerProducts:
			product.show_online = 0
			product.save()

class Migration(migrations.Migration):

	dependencies = [
		('catalog', '0016_auto_20170103_0745'),
		('users', '0060_auto_20161228_1241'),
	]

	operations = [
		migrations.RunPython(delete_to_show_online),
	]
