# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_buyerregistration_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('client_contact_id', models.IntegerField()),
                ('numbers', models.TextField(blank=True)),
                ('emails', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
            ],
            options={
                'verbose_name': 'Buyer Contacts Entry',
                'verbose_name_plural': 'Buyer Contacts Entries',
            },
        ),
    ]
