# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_buyercontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyercontacts',
            name='firebase_token',
            field=models.TextField(blank=True),
        ),
    ]
