# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160516_2252'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerleads',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='buyerleads',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactuslead',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactuslead',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
