# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20160520_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('mobile_number', models.CharField(blank=True, db_index=True, max_length=11)),
                ('status', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
