# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_sellerleads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerleads',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='contactuslead',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sellerleads',
            options={'ordering': ['-id']},
        ),
    ]
