# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20160623_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerleads',
            options={'ordering': ['-id'], 'verbose_name': 'Buyer Lead', 'verbose_name_plural': 'Buyer Leads'},
        ),
        migrations.AlterModelOptions(
            name='contactuslead',
            options={'ordering': ['-id'], 'verbose_name': 'Contact Us Lead', 'verbose_name_plural': 'Contact Us Leads'},
        ),
        migrations.AlterModelOptions(
            name='sellerleads',
            options={'ordering': ['-id'], 'verbose_name': 'Seller Lead', 'verbose_name_plural': 'Seller Leads'},
        ),
        migrations.AlterField(
            model_name='buyerleads',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='contactuslead',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='sellerleads',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
