# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-11 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20160719_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerleads',
            name='signup',
            field=models.BooleanField(default=True),
        ),
    ]
