# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_auto_20160702_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('show_online', models.BooleanField(default=True)),
                ('delete_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin_pulse_link', models.TextField(blank=True, null=True)),
                ('medium_link', models.TextField(blank=True, null=True)),
                ('tumblr_link', models.TextField(blank=True, null=True)),
                ('quora_link', models.TextField(blank=True, null=True)),
                ('blogspot_link', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.InternalUser')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
