# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlexaStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_rank', models.IntegerField(default=0)),
                ('india_rank', models.IntegerField(default=0)),
                ('bounce_rate', models.CharField(blank=True, max_length=20)),
                ('daily_page_views_per_visitor', models.CharField(blank=True, max_length=20)),
                ('daily_time_on_site', models.CharField(blank=True, max_length=20)),
                ('search_visits', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alexa Stats',
                'verbose_name_plural': 'Alexa Stats',
            },
        ),
    ]
