# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=11)),
                ('user_type', models.CharField(blank=True, max_length=30)),
                ('sms_purpose', models.CharField(blank=True, max_length=50)),
                ('message_text', models.TextField(blank=True)),
                ('message_count', models.IntegerField(default=1)),
                ('test_sms', models.BooleanField(default=0)),
                ('sending_success', models.BooleanField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=30)),
                ('delivered', models.BooleanField(default=0)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_provider', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'SMSSent',
                'verbose_name_plural': 'SMSSent',
            },
        ),
    ]
