# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-10 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20170110_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartMinValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cart Min Value',
                'verbose_name_plural': 'Cart Min Value',
            },
        ),
    ]
