# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_buyercontacts_firebase_token'),
        ('general', '0006_cartminvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=11)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('sharing_link', models.CharField(blank=True, max_length=100)),
                ('sharing_link_clicks', models.IntegerField(default=0)),
                ('sharing_link_click_time', models.DateTimeField(null=True)),
                ('message_sent_time', models.DateTimeField(null=True)),
                ('message_sent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.InternalUser')),
            ],
            options={
                'verbose_name': 'Marketing Contact',
                'verbose_name_plural': 'Marketing Contacts',
            },
        ),
    ]
