# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_marketingcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcontact',
            name='internal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.InternalUser'),
        ),
    ]
