# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20170214_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcontact',
            name='message_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingcontact',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='marketingcontact',
            name='sharing_link_click_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
