# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20170214_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcontact',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=11),
        ),
    ]
