# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_cartsellerminpieces'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('message_sent_time', models.DateTimeField(blank=True, null=True)),
                ('message_sent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unsubscribed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Marketing Email',
                'verbose_name_plural': 'Marketing Email',
            },
        ),
    ]
