# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-01 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_marketingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcontact',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
