# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
