# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160422_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_discount',
        ),
        migrations.RemoveField(
            model_name='productlot',
            name='lot_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='min_price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='fabric',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productlot',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
            preserve_default=False,
        ),
    ]
