# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160425_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='gsm',
            new_name='fabric_gsm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='fabric',
        ),
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.TextField(default='Temporary Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_numbers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='availability',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='dispatched_in',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='lot_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='manufactured_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='packaging_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='sample_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='sample_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='sample_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='weight_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
