# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 8, 15, 38, 59, 446774, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 8, 15, 39, 4, 784755, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
