# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20160615_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_in_product_matrix',
            field=models.BooleanField(default=True),
        ),
    ]
