# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20160719_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_online',
            field=models.BooleanField(default=True),
        ),
    ]
