# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_category_show_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
