# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 07:45
from __future__ import unicode_literals

from django.db import migrations

def delete_to_show_online(apps, schema_editor):

	Category = apps.get_model("catalog", "Category")
	Product = apps.get_model("catalog", "Product")

	products = Product.objects.filter(delete_status=1)

	for product in products:
		product.delete_status = 0
		product.show_online = 0
		product.save()

	categories = Category.objects.filter(delete_status=1)

	for category in categories:
		category.delete_status =0
		category.show_online = 0
		category.save()

		categoryProducts = Product.objects.filter(category_id=category.id)

		for product in categoryProducts:
			product.show_online = 0
			product.save()

class Migration(migrations.Migration):

	dependencies = [
		('catalog', '0015_category_image_url'),
	]

	operations = [
		migrations.RunPython(delete_to_show_online),
	]
