# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20170103_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_likes',
            field=models.IntegerField(default=0),
        ),
    ]
