# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-15 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20170114_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_score',
            field=models.DecimalField(decimal_places=4, default=50, max_digits=10),
        ),
    ]
