# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_product_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_score',
            field=models.DecimalField(db_index=True, decimal_places=4, default=50, max_digits=10),
        ),
    ]
