# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_auto_20160508_1540'),
        ('users', '0008_seller_seller_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.IntegerField(default=0)),
                ('payment_method', models.IntegerField(default=0)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.PositiveIntegerField(default=1)),
                ('undiscounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lots', models.PositiveIntegerField()),
                ('undiscounted_price_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_price_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot_size', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_status', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('cancellation_remarks', models.TextField(blank=True)),
                ('cancellation_time', models.DateTimeField(blank=True, null=True)),
                ('merchant_notified_time', models.DateTimeField(blank=True, null=True)),
                ('sent_for_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('lost_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('closed_time', models.DateTimeField(blank=True, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('logistics_partner', models.CharField(blank=True, max_length=50, null=True)),
                ('waybill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('packaged_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('packaged_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('packaged_breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('packaged_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('tpl_manifested_time', models.DateTimeField(blank=True, null=True)),
                ('tpl_in_transit_time', models.DateTimeField(blank=True, null=True)),
                ('tpl_stuck_in_transit_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('rto_in_transit_time', models.DateTimeField(blank=True, null=True)),
                ('rto_delivered_time', models.DateTimeField(blank=True, null=True)),
                ('rto_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BuyerAddress')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SellerAddress')),
            ],
        ),
        migrations.CreateModel(
            name='SellerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.IntegerField(default=0)),
                ('payment_method', models.IntegerField(default=0)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.PositiveIntegerField(default=1)),
                ('undiscounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='sellerpayment',
            name='suborder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SubOrder'),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='suborder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SubOrder'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderShipment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.SellerPayment'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='suborder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SubOrder'),
        ),
        migrations.AddField(
            model_name='buyerpayment',
            name='suborder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SubOrder'),
        ),
    ]
