# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160520_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordershipment',
            old_name='drop',
            new_name='drop_address',
        ),
        migrations.RenameField(
            model_name='ordershipment',
            old_name='pickup',
            new_name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='buyerpayment',
            name='suborder',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='undiscounted_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='actual_price_per_piece',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='closed_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cod_charge',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='completed_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='lost_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='merchant_notified_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sent_for_pickup_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_charge',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tracking_url',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='undiscounted_price_per_piece',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='undiscounted_price',
        ),
        migrations.AddField(
            model_name='buyerpayment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerpayment',
            name='payment_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='display_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='edited_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='calculated_price_per_piece',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='edited_price_per_piece',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pieces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='retail_price_per_piece',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='cod_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='current_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='lost_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='sent_for_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerpayment',
            name='payment_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suborder',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suborder',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='cod_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suborder',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='display_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='suborder',
            name='edited_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suborder',
            name='merchant_notified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suborder',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suborder',
            name='suborder_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='lots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
