# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160527_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='tpl_notified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='confirmed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
