# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160530_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerpayment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ordershipment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sellerpayment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='suborder',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='buyerpayment',
            name='order_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderShipment'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='manifest_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='suborder_payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
