# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20160609_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordershipment',
            old_name='logistics_partner',
            new_name='logistics_partner_name',
        ),
    ]
