# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordershipment_logistics_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pieces',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='buyer_payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suborder',
            name='cancellation_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='cancellation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='pieces',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
