# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20160713_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerpayment',
            options={'ordering': ['-id'], 'verbose_name': 'Buyer Payment', 'verbose_name_plural': 'Buyer Payments'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='ordershipment',
            options={'ordering': ['-id'], 'verbose_name': 'Order Shipment', 'verbose_name_plural': 'Order Shipments'},
        ),
        migrations.AlterModelOptions(
            name='sellerpayment',
            options={'ordering': ['-id'], 'verbose_name': 'Seller Payment', 'verbose_name_plural': 'Seller Payments'},
        ),
        migrations.AlterModelOptions(
            name='suborder',
            options={'ordering': ['-id'], 'verbose_name': 'Suborder', 'verbose_name_plural': 'Suborders'},
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='logistics_partner_name',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='packaged_breadth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='packaged_height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='packaged_length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='packaged_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='rto_remarks',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='tracking_url',
            field=models.URLField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='waybill_number',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
    ]
