# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cart_cartadmin_cartitem_cartitemhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_from_shortlist',
        ),
        migrations.RemoveField(
            model_name='cartitemhistory',
            name='added_from_shortlist',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='added_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitemhistory',
            name='added_from',
            field=models.IntegerField(default=0),
        ),
    ]
