# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20160808_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
