# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20160819_0612'),
        ('orders', '0016_auto_20160811_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_address_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BuyerAddressHistory'),
        ),
    ]
