# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20160819_0721'),
        ('orders', '0018_auto_20160819_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='seller_address_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SellerAddressHistory'),
        ),
    ]
