# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 10:11
from __future__ import unicode_literals

from django.db import migrations

def create_suborder_seller_address_history(apps, schema_editor):
	
	SubOrder = apps.get_model("orders","SubOrder")
	SellerAddressHistory = apps.get_model("users", "SellerAddressHistory")

	suborders = SubOrder.objects.filter(seller_address_history=None)

	for suborderPtr in suborders:
		try:
			sellerAddressHistoryPtr = SellerAddressHistory.objects.filter(seller=suborderPtr.seller).latest('created_at')
		except Exception, e:
			sellerAddressHistoryPtr = None
		suborderPtr.seller_address_history = sellerAddressHistoryPtr
		suborderPtr.save()


class Migration(migrations.Migration):

	dependencies = [
		('orders', '0019_suborder_seller_address_history'),
		('users', '0033_auto_20160819_0721')
	]

	operations = [
		migrations.RunPython(create_suborder_seller_address_history),
	]