# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20160819_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershipment',
            name='drop_address',
        ),
        migrations.RemoveField(
            model_name='ordershipment',
            name='pickup_address',
        ),
    ]
