# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20160819_0721'),
        ('orders', '0021_auto_20160819_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='drop_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BuyerAddressHistory'),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SellerAddressHistory'),
        ),
    ]
