# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 10:58
from __future__ import unicode_literals

from django.db import migrations

def create_order_shipment_addresses(apps, schema_editor):
	
	OrderShipment = apps.get_model("orders","OrderShipment")

	orderShipments = OrderShipment.objects.all()

	for orderShipmentPtr in orderShipments:
		orderShipmentPtr.pickup_address = orderShipmentPtr.suborder.seller_address_history
		orderShipmentPtr.drop_address = orderShipmentPtr.suborder.order.buyer_address_history
		orderShipmentPtr.save()


class Migration(migrations.Migration):

	dependencies = [
		('orders', '0022_auto_20160819_1052'),
	]

	operations = [
		migrations.RunPython(create_order_shipment_addresses),
	]
