# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_by',
            field=models.IntegerField(default=0),
        ),
    ]
