# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_placed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='label_link',
            field=models.TextField(blank=True),
        ),
    ]
