# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_ordershipment_label_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='pieces',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='product_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
