# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20160927_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='csv_link',
            field=models.TextField(blank=True),
        ),
    ]
