# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_ordershipment_csv_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordershipment',
            old_name='csv_link',
            new_name='soft_data_csv_link',
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='vendor_pickup_csv_link',
            field=models.TextField(blank=True),
        ),
    ]
