# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20160930_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcart',
            name='extra_shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
