# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_subcart_extra_shipping_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_by',
            field=models.CharField(max_length=100),
        ),
    ]
