# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 17:58
from __future__ import unicode_literals

from django.db import migrations

def changed_placed_by_order(apps, schema_editor):

	Order = apps.get_model("orders", "Order")

	Order.objects.all().update(placed_by="Admin")
	

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20170106_1756'),
    ]

    operations = [
    	migrations.RunPython(changed_placed_by_order)
    ]
