# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20170207_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcart',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
